<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>Cambodian prime minister Hun Sen rejects demands of 2 opposition parties for talks in Beijing after failing to win a 2/3 majority in recent elections.</a>
<a name="2">[2]</a> <a href="#2" id=2>Sihanouk refuses to host talks in Beijing.</a>
<a name="3">[3]</a> <a href="#3" id=3>Opposition parties ask the Asian Development Bank to stop loans to Hun Sen's government.</a>
<a name="4">[4]</a> <a href="#4" id=4>CCP defends Hun Sen to the US Senate.</a>
<a name="5">[5]</a> <a href="#5" id=5>FUNCINPEC refuses to share the presidency.</a>
<a name="6">[6]</a> <a href="#6" id=6>Hun Sen and Ranariddh eventually form a coalition at summit convened by Sihanouk.</a>
<a name="7">[7]</a> <a href="#7" id=7>Hun Sen remains prime minister, Ranariddh is president of the national assembly, and a new senate will be formed.</a>
<a name="8">[8]</a> <a href="#8" id=8>Opposition leader Rainsy left out.</a>
<a name="9">[9]</a> <a href="#9" id=9>He seeks strong assurance of safety should he return to Cambodia.</a>
<a name="10">[10]</a> <a href="#10" id=10></a>
</body>
</html>