<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>Cambodian elections, fraudulent according to opposition parties, gave the CPP of Hun Sen a scant majority but not enough to form its own government.</a>
<a name="2">[2]</a> <a href="#2" id=2>Opposition leaders fearing arrest, or worse, fled and asked for talks outside the country.</a>
<a name="3">[3]</a> <a href="#3" id=3>Han Sen refused.</a>
<a name="4">[4]</a> <a href="#4" id=4>The UN found evidence of rights violations by Hun Sen prompting the US House to call for an investigation.</a>
<a name="5">[5]</a> <a href="#5" id=5>The three-month governmental deadlock ended with Han Sen and his chief rival, Prince Norodom Ranariddh sharing power.</a>
<a name="6">[6]</a> <a href="#6" id=6>Han Sen guaranteed safe return to Cambodia for all opponents but his strongest critic, Sam Rainsy, remained wary.</a>
<a name="7">[7]</a> <a href="#7" id=7>Chief of State King Norodom Sihanouk praised the agreement.</a>
<a name="8">[8]</a> <a href="#8" id=8></a>
</body>
</html>