<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>Honduras braced as category 5 Hurricane Mitch approached.</a>
<a name="2">[2]</a> <a href="#2" id=2>Slow-moving Mitch battered the Honduran coast for 3 days.</a>
<a name="3">[3]</a> <a href="#3" id=3>Honduran death estimates grew from 32 to 231 in the first days, to 6,076, with 4,621 missing.</a>
<a name="4">[4]</a> <a href="#4" id=4>About 2,000 were killed in Nicaragua, 239 in El Salvador, 194 in Guatemala, 6 in southern Mexico and 7 in Costa Rica.</a>
<a name="5">[5]</a> <a href="#5" id=5>The EU approved 6.4 million ecu in aid to Mitch's victims.</a>
<a name="6">[6]</a> <a href="#6" id=6>The Pope appealed for aid.</a>
<a name="7">[7]</a> <a href="#7" id=7>The US boosted aid to $70 million.</a>
<a name="8">[8]</a> <a href="#8" id=8>A id workers struggled to reach survivors in danger.</a>
<a name="9">[9]</a> <a href="#9" id=9>Hurricane winds, rain and floods caused massive damage to homes, businesses, roads and bridges.</a>
<a name="10">[10]</a> <a href="#10" id=10>Latest reports estimate over 10,000 killed in Central America.</a>
<a name="11">[11]</a> <a href="#11" id=11></a>
</body>
</html>