<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>A category 5 storm, Hurricane Mitch roared across the northwest Caribbean with 180 mph winds across a 350-mile front that devastated the mainland and islands of Central America.</a>
<a name="2">[2]</a> <a href="#2" id=2>Although the force of the storm diminished, at least 8,000 people died from wind, waves and flood damage.</a>
<a name="3">[3]</a> <a href="#3" id=3>The greatest losses were in Honduras where some 6,076 people perished.</a>
<a name="4">[4]</a> <a href="#4" id=4>Around 2,000 people were killed in Nicaragua, 239 in El Salvador, 194 in Guatemala, seven in Costa Rica and six in Mexico.</a>
<a name="5">[5]</a> <a href="#5" id=5>At least 569,000 people were homeless across Central America.</a>
<a name="6">[6]</a> <a href="#6" id=6>Aid was sent from many sources (European Union, the UN, US and Mexico).</a>
<a name="7">[7]</a> <a href="#7" id=7>Relief efforts are hampered by extensive damage.</a>
<a name="8">[8]</a> <a href="#8" id=8></a>
</body>
</html>