<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>Pinochet arrested in London on Oct. 16 at a Spanish judge's request for atrocities against Spaniards in Chile during his rule.</a>
<a name="2">[2]</a> <a href="#2" id=2>Castro, Chilean legislators and Pinochet's lawyers protested and claimed he had diplomatic immunity.</a>
<a name="3">[3]</a> <a href="#3" id=3>His wife asked for his release because he was recovering from recent back surgery.</a>
<a name="4">[4]</a> <a href="#4" id=4>Pinochet visited Thatcher before his surgery.</a>
<a name="5">[5]</a> <a href="#5" id=5>The British and Spanish governments defended the arrest, saying it was strictly a legal matter.</a>
<a name="6">[6]</a> <a href="#6" id=6>The EC president hoped Pinochet would stand trial.</a>
<a name="7">[7]</a> <a href="#7" id=7>None of his Swiss accounts have been frozen yet.</a>
<a name="8">[8]</a> <a href="#8" id=8>The Swiss government also asked for his arrest for the 1977 disappearance of a Swiss-Chilean student.</a>
<a name="9">[9]</a> <a href="#9" id=9></a>
</body>
</html>