<html>
<head>
<title>dummy title</title>
</head>
<body bgcolor="white">
<a name="1">[1]</a> <a href="#1" id=1>Following the bombings of the embassies in Africa, the US began a full-scale assault on Osama bin Laden.</a>
<a name="2">[2]</a> <a href="#2" id=2>Attacked were a chemical plant in the Sudan and a camp in Afghanistan where he was believed to be, creating an assassination opportunity.</a>
<a name="3">[3]</a> <a href="#3" id=3>Evidence was gathered from a captured computer and an in-law who defected.</a>
<a name="4">[4]</a> <a href="#4" id=4>Suspects were identified and the FBI began to build a case in New York.</a>
<a name="5">[5]</a> <a href="#5" id=5>Extradition of a suspect from Germany was sought.</a>
<a name="6">[6]</a> <a href="#6" id=6>Reactions from Islamic nations varied: Afghanistan promised him safe haven; more liberal Bandladesh arrested pro-Taliban reporters; Albania feared it was an infiltration center for the rest of Europe, including Kosovo.</a>
<a name="7">[7]</a> <a href="#7" id=7></a>
</body>
</html>